---
title: "Bennett Kleinberg"
output:
  html_document:
    css: "./css/retro.css"
---





I am an Associate Professor in Behavioural Data Science at the [Department of Methodology and Statistics](https://www.tilburguniversity.edu/about/schools/socialsciences/organization/departments/methodology-statistics) at Tilburg University (The Netherlands) and the [Department of Security and Crime Science](https://www.ucl.ac.uk/engineering/security-crime-science) at University College London (UK).

Previously I held a position at the [UCL Dawes Centre for Future Crime](https://www.ucl.ac.uk/engineering/future-crime) and obtained my PhD from the [Department of Psychology](https://www.uva.nl/en/about-the-uva/organisation/faculties/faculty-of-social-and-behavioural-sciences/organisation/disciplines/psychology.html) at the University of Amsterdam.

---

My research revolves around the interplay and advancement of psychological research and computational methods to study human behaviour. 

I seek to answer two questions:  

1. **How can computational methods enhance our understanding of the human mind and behaviour?**
2. **How can psychological research methods inform our understanding of computational model behaviour?**


Substantive research interests include: 

- Deception detection and legal psychology
- Human resilience
- Machine behaviour 

With our ERC Synergy Grant for our project [JUSTICE](https://www.tilburguniversity.edu/current/news/more-news/tilburg-researcher-receives-prestigious-erc-synergy-grant-help-end-coercive-interrogations), part of my research will focus on computational legal psychology to combine human and artificial intelligence for evidence-based and human rights-compliant investigatve interviewing.

In our [Computational Psychology and Computational Methods (CPCM) Lab](https://cpcm-lab.net/), we collect data in psychological experiments and develop and apply techniques from natural language processing, (adversarial) machine learning, and statistical modelling to better understand human behaviour and psychological processes.

You can find an overview of papers on [Google Scholar](https://scholar.google.com/citations?user=Ms2d7OsAAAAJ&hl=en) and some [additional outputs here](./output.html). Sometimes [media](./media.html) outlets cover our work.

I am [teaching](./teaching.html) in various programmes. Most of the course materials are available online.


---

### Updates

- We're running a special session at [XAI 2026](https://xaiworldconference.com/2026/) on [psychometrics applied to AI research](https://xaiworldconference.com/2026/psychometric-applications-for-xai/). CfP open soon. Contact me or the lead organisers [Sanne Peereboom](https://sannepeereboom.com/) and [Nicola Rossberg](https://www.crt-ai.ie/team/nicola-c-rossberg/).
- Our special issue in Legal and Criminological Psychology on the [Impact of Artificial Intelligence and New Technologies on Legal and Criminological Psychology](https://bpspsychub.onlinelibrary.wiley.com/hub/journal/20448333/call-for-papers/si-2025-001204) is open for submissions. For any questions, reach out to me or Riccardo Loconte.
- We've launched our 2-year master track [AI for Psychological Research](https://www.tilburguniversity.edu/education/masters-programs/artificial-intelligence-psychological-research). If you're interested in applying or have got other questions, please reach out.


---

#### Common questions

- _Is it possible to do a PhD with you?_ Yes. There are various routes for PhD projects (e.g., a funded position via university employment, a joint PhD with another university, self-funding). All positions that are connected to employment (typically for 4 years) are publicly advertised. If you are keen to explore options, please have a look at our lab and my research areas. The PhD project should be aligned with the overall focus on computational methods to study human behaviour and psychology.
- _How can I join the research lab?_ The lab members are PhD students, thesis students or research interns/assistants. If you are looking for a thesis project, see below. For PhD opportunities, see above. If you are interested in a research internship, please identify a topic you are interested in that aligns with the lab's focus and is relevant to me and at least one other lab member. Reach out to me via email then. Research internships should last at least 6 months.
- _Do you offer projects for a bachelor theses?_ Projects for BSc projects are advertised in the relevant BSc programmes and solely work through that route.
- _Can I do my MSc thesis in your lab?_ Yes - if your interests align with the focus of the lab. Please identify a relevant question you want to work on and contact me. The positions in the lab are limited to ensure close supervision.
- _Would you write a letter of recommendation for me?_ If you are student and need a letter of recommendation for a masters programme (or other programmes), I am happy to write that letter for you _if I know you_. The best way for me to write a letter of reference is if you have spent some time in our lab.

