---
title: ""
output:
  html_document:
    css: "./css/retro.css"
---

Every now and then our research is covered by media outlets. A selection of that coverage is listed below.



#### Print/online media

- Nemo Kennislink (Dutch) (2024), Zien is niet geloven. Verkeerd gedacht: AI-beeld, [https://www.nemokennislink.nl/publicaties/zien-is-niet-geloven/](https://www.nemokennislink.nl/publicaties/zien-is-niet-geloven/)
- Daily Mail (2023), The new way to spot LIAR according to researchers, [https://www.dailymail.co.uk/sciencetech/article-11885973/The-new-way-spot-LIAR-according-researchers.html](https://www.dailymail.co.uk/sciencetech/article-11885973/The-new-way-spot-LIAR-according-researchers.html)
- European Scientist (2023), A new way to catch liars, [https://www.europeanscientist.com/en/research/a-new-way-to-catch-liars/](https://www.europeanscientist.com/en/research/a-new-way-to-catch-liars/)
- New Scientist (2023), Is someone lying to you? A lack of detail may give them away, [https://www.newscientist.com/article/2365049-is-someone-lying-to-you-a-lack-of-detail-may-give-them-away/](https://www.newscientist.com/article/2365049-is-someone-lying-to-you-a-lack-of-detail-may-give-them-away/)
- New York Post (2023), Here's how to tell if someone is lying to you, [https://nypost.com/2023/04/03/heres-how-to-tell-if-someone-is-lying-to-you/](https://nypost.com/2023/04/03/heres-how-to-tell-if-someone-is-lying-to-you/)
- TiU press release (2021), Detect mental problems with text data, [https://www.tilburguniversity.edu/magazine/detect-mental-problems-text-data](https://www.tilburguniversity.edu/magazine/detect-mental-problems-text-data)
- Discover Magazine (2020), The Curious Case of Drill Rap and Its Link to Violent Crime, [https://www.discovermagazine.com/the-sciences/the-curious-case-of-drill-rap-and-its-link-to-violent-crime](https://www.discovermagazine.com/the-sciences/the-curious-case-of-drill-rap-and-its-link-to-violent-crime)
- Daily Mail (2020), Men worry about the economy and COVID-19 while women are more concerned about loved ones, [https://www.dailymail.co.uk/sciencetech/article-8316235/Men-worry-economy-COVID-19-women-concerned-loved-ones.html](https://www.dailymail.co.uk/sciencetech/article-8316235/Men-worry-economy-COVID-19-women-concerned-loved-ones.html)
- UCL News (2020), How men and women's anxieties differ over COVID-19, [https://www.ucl.ac.uk/news/2020/may/how-men-and-womens-anxieties-differ-over-covid-19](https://www.ucl.ac.uk/news/2020/may/how-men-and-womens-anxieties-differ-over-covid-19)
- UCL News (2019), Positive drill music receives more audience engagement, [https://www.ucl.ac.uk/news/headlines/2019/nov/positive-drill-music-receives-more-audience-engagement](https://www.ucl.ac.uk/news/headlines/2019/nov/positive-drill-music-receives-more-audience-engagement)
- New Scientist (2019), Drill music with positive lyrics is more popular than negative songs, [https://www.newscientist.com/article/2223723-drill-music-with-positive-lyrics-is-more-popular-than-negative-songs](https://www.newscientist.com/article/2223723-drill-music-with-positive-lyrics-is-more-popular-than-negative-songs/)
- The Times (2019), Met police and scientists developing way to decipher violent threats in drill videos, [https://www.thetimes.co.uk/article/met-police-and-scientists-developing-way-to-decipher-voilent-threats-in-drill-videos-fzc6t9rlq](https://www.thetimes.co.uk/article/met-police-and-scientists-developing-way-to-decipher-voilent-threats-in-drill-videos-fzc6t9rlq)
- Ulyces (French) (2019), Drill UK: des roulements de caisses claires et des meurtres au couteau, [https://www.ulyces.co/denis-hadzovic/drill-uk-des-roulements-de-caisses-claires-et-des-meurtres-au-couteau](https://www.ulyces.co/denis-hadzovic/drill-uk-des-roulements-de-caisses-claires-et-des-meurtres-au-couteau/)
- Folia Magazine (Dutch) (2019), Dialogen met chatbots kunnen helpen in strijd tegen terrorisme, [https://www.folia.nl/wetenschap/126359/dialogen-met-chatbots-kunnen-helpen-in-strijd-tegen-terrorisme](https://www.folia.nl/wetenschap/126359/dialogen-met-chatbots-kunnen-helpen-in-strijd-tegen-terrorisme)
- SAGE Ocean press release (2019), SAGE Ocean announces Text Wash as 2019 Concept Grant winner, [https://uk.sagepub.com/en-gb/eur/press/sage-ocean-announces-text-wash-as-2019-concept-grant-winner](https://uk.sagepub.com/en-gb/eur/press/sage-ocean-announces-text-wash-as-2019-concept-grant-winner)
- Deutsche Welle (German) (2018), EU testet Lügendetektor an Außengrenzen, [https://www.dw.com/de/eu-testet-l%C3%BCgendetektor-an-au%C3%9Fengrenzen/a-46195158](https://www.dw.com/de/eu-testet-l%C3%BCgendetektor-an-au%C3%9Fengrenzen/a-46195158)
- New Scientist (2018), An AI lie detector will interrogate travellers at some EU borders, [https://www.newscientist.com/article/mg24032023-400-an-ai-lie-detector-will-interrogate-travellers-at-some-eu-borders/](https://www.newscientist.com/article/mg24032023-400-an-ai-lie-detector-will-interrogate-travellers-at-some-eu-borders/)
- Süddeutsche Zeitung (German) (2018), Grenze: Künstliche Intelligenz Software IBorderCtrl, [https://www.sueddeutsche.de/digital/grenze-kuenstliche-intelligenz-software-iborderctrl-1.4196243](https://www.sueddeutsche.de/digital/grenze-kuenstliche-intelligenz-software-iborderctrl-1.4196243)
- The Guardian (2018), EU border lie detection system criticised as pseudoscience, [https://www.theguardian.com/world/2018/nov/02/eu-border-lie-detection-system-criticised-as-pseudoscience](https://www.theguardian.com/world/2018/nov/02/eu-border-lie-detection-system-criticised-as-pseudoscience)
- Volkskrant (Dutch) (2018), EU zet omstreden AI-leugendetector in bij grenscontrole, [https://www.volkskrant.nl/nieuws-achtergrond/eu-setomstreden-ai-leugendetector-in-bij-grenscontrole~b169bb03](volkskrant.nl)
- APA News (2016), Judge Truthfulness, [http://www.apa.org/news/press/releases/2016/06/judge-truthfulness.aspx](http://www.apa.org/news/press/releases/2016/06/judge-truthfulness.aspx)
- Psychology Today (2016), What Is the Face of Truth?, [https://www.psychologytoday.com/blog/brainstorm/201608/what-is-the-face-truth](https://www.psychologytoday.com/blog/brainstorm/201608/what-is-the-face-truth)


#### Video, radio, podcasts

- [NTR Wetenschap interview](https://www.youtube.com/watch?v=C-sqX8DLs-0)
- [YouTube production from SAGE](https://www.youtube.com/watch?v=T9pRRn2DrMY)
- BBC Newsroom, BNR Newsradio
- [Amsterdam FM (Dutch)](http://www.radioswammerdam.nl/op-het-slechte-pad-i-leugentje-om-je-eigen-bestwil/)

